### ISSUE TITLE
browser.newContext: Protocol error

### ISSUE THREAD

**Issue by jt9ge** [carcabot/tiktok-signature#145]
**Describe the bug**

```
com_tiktok_signature  | browser.newContext: Protocol error (Target.createBrowserContext): Browser closed.
com_tiktok_signature  | ==================== Browser output: ====================
com_tiktok_signature  | [pid=32][err] [0312/195116.029402:ERROR:bus.cc(393)] Failed to connect to the bus: Failed to connect to socket /var/run/dbus/system_bus_socket: No such file or directory
com_tiktok_signature  | [pid=32][err] [0312/195116.044681:ERROR:file_path_watcher_linux.cc(316)] inotify_init() failed: Function not implemented (38)
com_tiktok_signature  | [pid=32][err] Received signal 11 SEGV_MAPERR 061d00000624
com_tiktok_signature  | [pid=32][err] #0 0x0040062c9c49 [0312/195116.147804:WARNING:gpu_process_host.cc(1296)] The GPU process has crashed 1 time(s)
com_tiktok_signature  | [pid=32][err] [0312/195116.167359:WARNING:gpu_process_host.cc(1296)] The GPU process has crashed 2 time(s)
com_tiktok_signature  | [pid=32][err] [0312/195116.174505:WARNING:gpu_process_host.cc(1296)] The GPU process has crashed 3 time(s)
com_tiktok_signature  | [pid=32][err] [0312/195116.180760:WARNING:gpu_process_host.cc(1296)] The GPU process has crashed 4 time(s)
com_tiktok_signature  | [pid=32][err] [0312/195116.183291:WARNING:gpu_process_host.cc(1296)] The GPU process has crashed 5 time(s)
com_tiktok_signature  | [pid=32][err] [0312/195116.185764:WARNING:gpu_process_host.cc(1296)] The GPU process has crashed 6 time(s)
com_tiktok_signature  | [pid=32][err] [0312/195116.190509:WARNING:gpu_process_host.cc(1296)] The GPU process has crashed 7 time(s)
com_tiktok_signature  | [pid=32][err] base::debug::CollectStackTrace()
com_tiktok_signature  | [pid=32][err] #1 0x004006237ab3 [0312/195116.222283:WARNING:gpu_process_host.cc(1296)] The GPU process has crashed 8 time(s)
com_tiktok_signature  | [pid=32][err] [0312/195116.276322:WARNING:gpu_process_host.cc(1296)] The GPU process has crashed 9 time(s)
com_tiktok_signature  | [pid=32][err] base::debug::StackTrace::StackTrace()
com_tiktok_signature  | [pid=32][err] #2 0x0040062c97f0 base::debug::(anonymous namespace)::StackDumpSignalHandler()
com_tiktok_signature  | [pid=32][err] #3 0x00400dd7b980 <unknown>
com_tiktok_signature  | [pid=32][err] #4 0x00400d93522e <unknown>
com_tiktok_signature  | [pid=32][err] #5 0x00400d9371ac <unknown>
com_tiktok_signature  | [pid=32][err] #6 0x00400d943084 <unknown>
com_tiktok_signature  | [pid=32][err] #7 0x00401338016f _dl_catch_exception
com_tiktok_signature  | [pid=32][err] #8 0x00400d94296a <unknown>
com_tiktok_signature  | [pid=32][err] #9 0x00400db63f96 <unknown>
com_tiktok_signature  | [pid=32][err] #10 0x00401338016f _dl_catch_exception
com_tiktok_signature  | [pid=32][err] #11 0x0040133801ff _dl_catch_error
com_tiktok_signature  | [pid=32][err] #12 0x00400db64745 <unknown>
com_tiktok_signature  | [pid=32][err] #13 0x00400db64051 dlopen
com_tiktok_signature  | [pid=32][err] #14 0x004003b9eba0 LibUdev0Loader::Load()
com_tiktok_signature  | [pid=32][err] #15 0x004003b9db44 device::Udev1Loader::Init()
com_tiktok_signature  | [pid=32][err] #16 0x004003b9dba9 device::UdevLoader::Get()
com_tiktok_signature  | [pid=32][err] #17 0x004003b9d279 device::udev_new()
com_tiktok_signature  | [pid=32][err] #18 0x004003b9df37 device::UdevWatcher::StartWatching()
com_tiktok_signature  | [pid=32][err] #19 0x004003c4fb19 media::DeviceMonitorLinux::BlockingTaskRunnerHelper::Initialize()
com_tiktok_signature  | [pid=32][err] #20 0x00400628c008 base::TaskAnnotator::RunTask()
com_tiktok_signature  | [pid=32][err] #21 0x0040062a3047 base::internal::TaskTracker::RunContinueOnShutdown()
com_tiktok_signature  | [pid=32][err] #22 0x0040062a2b6a base::internal::TaskTracker::RunTask()
com_tiktok_signature  | [pid=32][err] #23 0x0040062d9f1c base::internal::TaskTrackerPosix::RunTask()
com_tiktok_signature  | [pid=32][err] #24 0x0040062a2797 base::internal::TaskTracker::RunAndPopNextTask()
com_tiktok_signature  | [pid=32][err] #25 0x0040062aebb6 base::internal::WorkerThread::RunWorker()
com_tiktok_signature  | [pid=32][err] #26 0x0040062ae8bd base::internal::WorkerThread::RunPooledWorker()
com_tiktok_signature  | [pid=32][err] #27 0x0040062da76f base::(anonymous namespace)::ThreadFunc()
com_tiktok_signature  | [pid=32][err] #28 0x00400dd706db start_thread
com_tiktok_signature  | [pid=32][err] #29 0x00401333a61f clone
com_tiktok_signature  | [pid=32][err]   r8: 000000006fffffff  r9: 0000000070000021 r10: 0000000000000031 r11: 000000006ffffdff
com_tiktok_signature  | [pid=32][err]  r12: 000000037ffff1a0 r13: 000000401f619a68 r14: 000000006ffffeff r15: 00000000000000d1
com_tiktok_signature  | [pid=32][err]   di: 0000004022e2e000  si: 0000000000000028  bp: 000000401f619980  bx: 00002324003ec000
com_tiktok_signature  | [pid=32][err]   dx: 0000000000000000  ax: 0000061d0000061c  cx: 00002324003ec040  sp: 000000401f619840
com_tiktok_signature  | [pid=32][err]   ip: 000000400d93522e efl: 0000000000000202 cgf: 002b000000000033 erf: 0000000000000004
com_tiktok_signature  | [pid=32][err]  trp: ffffffffffffffff msk: 0000000000000000 cr2: 0000061d00000624
com_tiktok_signature  | [pid=32][err] [end of stack trace]
com_tiktok_signature  | [pid=32][err] Calling _exit(1). Core file will not be generated.
com_tiktok_signature  | Error
com_tiktok_signature  |     at Object.captureStackTrace (/usr/node_modules/playwright-chromium/lib/utils/stackTrace.js:48:19)
com_tiktok_signature  |     at Connection.sendMessageToServer (/usr/node_modules/playwright-chromium/lib/client/connection.js:69:48)
com_tiktok_signature  |     at Proxy.<anonymous> (/usr/node_modules/playwright-chromium/lib/client/channelOwner.js:64:61)
com_tiktok_signature  |     at /usr/node_modules/playwright-chromium/lib/client/browser.js:43:81
com_tiktok_signature  |     at async ChromiumBrowser._wrapApiCall (/usr/node_modules/playwright-chromium/lib/client/channelOwner.js:77:28)
com_tiktok_signature  | Received url: https://vt.tiktok.com/ZSdJGu2ce/
com_tiktok_signature  | TypeError: Cannot read property 'evaluate' of undefined
com_tiktok_signature  |     at Signer.sign (/usr/index.js:112:33)
com_tiktok_signature  |     at IncomingMessage.<anonymous> (/usr/listen.js:47:39)
com_tiktok_signature  |     at IncomingMessage.emit (events.js:314:20)
com_tiktok_signature  |     at endReadableNT (_stream_readable.js:1241:12)
com_tiktok_signature  |     at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

## If fields below will be empty then issue will be Ignored and Closed

**To Reproduce**
- Mac M1
- Docker --platform=linux/amd64
- github master branch (2022.03.12)

**Screenshots**

**Comment by JqyModi** [comment]
@jt9ge I have encountered similar problems. Can you share your solutions
