### ISSUE TITLE
Node server won't start - giving unexpected token error

### ISSUE THREAD

**Issue by Alblanca** [carcabot/tiktok-signature#40]
After cloning the repository and installing dependencies, it happens when I try to run the server:
`node listen.js`

`c:\git\experiment\tiktok-signature\index.js:9
  userAgent =
            ^

SyntaxError: Unexpected token =
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (c:\git\experiment\tiktok-signature\listen.js:1:16)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)`

Am I missing something?  

Thank you!

**Comment by Alblanca** [comment]
Woops, I found that the reason was to do with my local node version (I had to downgrade it at some point and didn't realize)

Running it after upgrading my node to 14.2.0 worked
