### ISSUE TITLE
TimeOut Browser.js

### ISSUE THREAD

**Issue by andrenjdev** [carcabot/tiktok-signature#46]
Hi,
on my local server, it works well but in production, it goes in timeout.
Can my server's IP be banned? How I can test it?

Thank you!
I receive this error message:

```
node node_modules/tiktok-signature/browser.js "https://m.tiktok.com/api/item_list/?count=20&id=6751746612202537990&type=1&maxCursor=0&minCursor=0&sourceType=8&appId=1233&region=IT&language=it&verifyFp="
TimeoutError: Navigation timeout of 30000 ms exceeded
    at /home/forge/###/node_modules/puppeteer/lib/LifecycleWatcher.js:100:111
  -- ASYNC --
    at Frame.<anonymous> (/home/forge/###/node_modules/puppeteer/lib/helper.js:94:19)
    at Page.goto (/home/forge/###/node_modules/puppeteer/lib/Page.js:476:53)
    at Page.<anonymous> (/home/forge/###/node_modules/puppeteer/lib/helper.js:95:27)
    at Signer.init (/home/forge/###/node_modules/tiktok-signature/index.js:63:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async main (/home/forge/###/node_modules/tiktok-signature/browser.js:8:9)
```

**Comment by anpato** [comment]
Set up a cron job every 12 hours or so to restart your server.
