### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by fracogno** [carcabot/tiktok-signature#59]
Hey there!

I was trying to run the repository using Docker.

Steps:
1 - Clone the repo
2 - Build a docker image from inside the repo using Dockerfile
3 - Run docker created image

I get the following error:

2020-06-07T08:55:33: PM2 log: App [listen:0] starting in -fork mode-
2020-06-07T08:55:33: PM2 log: App [listen:0] online
Error: Cannot find module 'playwright'
Require stack:
- /usr/app/index.js
- /usr/app/listen.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/app/index.js:1:29)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/app/index.js', '/usr/app/listen.js' ]
}

It seems that the playwright module isn't install, but inside the package*.json files it is contained, so I'd assume it's already in it. I also tried to run npm -i playwright, but it throws the same error when I run the docker image.

Have you guys run into this kind of issue?
Cheers!

**Comment by LSeiei** [comment]
Me too
I found that after using -v $(pwd):/usr/app, /usr/app/node_modules in docker no longer exists

**Comment by fracogno** [comment]
The problem is that when we use the volume (-v) running the docker image, the volume folder overwrites the content of the folder /usr/app inside the container.

Solution:
1. In the Dockerfile replace COPY package*.json ./ with COPY ./ ./
2. when running the volume remove shared volume
